# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'dotnet tool install -g dotnet-script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'script'
    arguments: 'changelogger.csx example/project1'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "changelogger@example.com"
      git config --global user.name "Changelogger"
      git commit -a -m "Generated changelog.md [skip ci]"
      git push origin HEAD:$(Build.SourceBranch)

- task: mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/ziphil-net/changelogger/_git/changelogger/'
    sourceGitRepositoryPersonalAccessToken: '$(azureDevOpsSourcePersonalAccessToken)'
    sourceVerifySSLCertificate: false
    sourceGitRepositoryCloneDirectoryName: '.git-to-mirror'
    destinationGitRepositoryUri: 'https://github.com/z1ph/changelogger.git'
    destinationGitRepositoryPersonalAccessToken: '$(githubPersonalAccessToken)'